from enum import Enum


class DisplayZoneType(Enum):
	DEFAULT_DISPLAY_ZONE = 0
	IMAGINARY_PART_DISPLAY_ZONE = 1
	REAL_PART_DISPLAY_ZONE = 2
	PHASE_DISPLAY_ZONE = 3
	MODULE_DISPLAY_ZONE = 4
	YZ_DISPLAY_ZONE = 5
	XY_DISPLAY_ZONE = 6
	ORDER_SECTION_ZONE = 7
	_3D_ZONE = 8
