from .adddatatotcpresultchannel import *
from .addresulttosetup import *
from .changetcpresultname import *
from .createresultex import *
from .createresultrecordsignal import *
from .createtcpresultchannel import *
from .deleteallresultex import *
from .deleteallresultrecordsignal import *
from .deleteresultex import *
from .deleteresultrecordsignal import *
from .export import *
from .getavailableresultlist import *
from .getresultcaption import *
from .getresultex import *
from .getresultrecordsignalblock import *
from .getresultrecordsignalzoom import *
from .getresultlist import *
from .getsavedresultlist import *
from .getsignalproperties import *
from .gettcpresult import *
from .gettcpresultchannellist import *
from .getwtfresultlist import *
from .importfile import *
from .issignalfilecompatible import *
from .newdatafortcpresultchannel import *
from .removesetupresult import *
from .removetcpresultchannel import *
from .saveresults import *
from .setsetupparameters import *
from .settcpresultchannel import *

from .createresultrecordsignal import *
from .deleteresultrecordsignal import *
from .deleteallresultrecordsignal import *
from .getresultrecordsignalblock import *
